project_id = "jdtqgaetldlxhvjojfze"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://jdtqgaetldlxhvjojfze.supabase.co"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false
template = "Your code is {{ .Code }} ."

[functions.ingest-news]
verify_jwt = false

[functions.story-analyzer]
verify_jwt = false

[functions.cluster-articles]
verify_jwt = false

[functions.generate-feed]
verify_jwt = false

[functions.ad-analytics]
verify_jwt = true

[functions.get-ad-display]
verify_jwt = false

[functions.get-adsense-config]
verify_jwt = true

[functions.verifier-agent]
verify_jwt = false

[functions.contextualizer-agent]
verify_jwt = false

[functions.analyst-agent]
verify_jwt = false

[functions.impact-agent]
verify_jwt = false

[functions.content-formatter]
verify_jwt = false