// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdtqgaetldlxhvjojfze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkdHFnYWV0bGRseGh2am9qZnplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNDE2MTUsImV4cCI6MjA2NTcxNzYxNX0.Wo9vYp_SShsHyNcohnQUy16tM1FlFe4fBJLxYtX8-0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);